create database info;
use info;
create table students(std_id int primary key auto_increment,std_name varchar(50),email varchar(100), age int, dept varchar(100));
insert into students(std_name, email,age,dept) values("keerthi","keerthi@gmail.com", 23,"hr"),("riya","riya@gmail.com",24,"finance"),("akki","akki@gmail.com",25,"logistics"),("devu","devu@gmail.com",22,"hr"),("anu","anu@gmail.com",25,"sales");
select * from students;
create table customers(ctm_id int primary key auto_increment, ctm_FN varchar(100), ctm_LN varchar(100), ctm_email varchar(50), purchase_amt int);
insert into customers(ctm_FN, ctm_LN, ctm_email,purchase_amt) values("riya","R", "riyar@gmail.com",50000),("akki","P","akkip@gmail.com",45000),("dhiya","eldho","diyaeldho@gmail.com",60000),("amitha","girish","aami@gmail.com",25000);
select * from customers;
create table sales(order_id int primary key auto_increment, ctm_id int , product varchar(50), quantity int, amount int);
insert into sales(ctm_id,product,quantity,amount) values(1,"mobile",100,50000),(2,"laptop",50,25000),(3,"tablet",150,150000),(4,"watch",300,95000);
select * from sales;
update students set dept ='operations' where std_id=2;
update students set age=23, dept='finance' where std_id=5;
delete from students where std_id= 1;
delete from students where age<20;
select distinct dept as dept_name from students where age>18;
select * from students where age between 18 and 22;
select * from students where dept in ('hr', 'finance');
select * from students where not dept='history';
select * from students where email is null;
select std_name from students where std_name like '%an%';
select ctm_FN as fname from customers;
select * from customers order by ctm_LN;
select * from customers order by purchase_amt limit 5;
select count(order_id) as total_sales from sales;
select sum(amount) as total_revenue from sales;
select min(amount) as min_amount from sales;
select max(amount) as max_amount from sales;
delete from students;
truncate table students;
drop table students;

