create database product;
use product;
create table sales(order_id int primary key auto_increment,region varchar(50), prct varchar(50), amount int);
insert into sales(region,prct,amount)values("kannur","laptop",3000),("kollam","watches",6000),("trivandrum","phones",40000),("kochi","tablets",25000);
select * from sales;
select region, sum(amount) as total_sales from sales group by region;
select prct, avg(amount) as avg_sales from sales group by prct;
select region, sum(amount) as total_sales from sales group by region having sum(amount>100000);
select prct, avg(amount) as avg_sales from sales group by prct having avg(amount)>10000;
create table customer(cstm_id int, cstm_name varchar(100));
insert into customer(cstm_id,cstm_name)values(01,"keerthi"),(02,"riya"),(03,"dhiya");
select * from customer;
create table orders(order_id int, cstm_id int, order_amount int);
insert into orders(order_id,cstm_id,order_amount)values(101,01,20000),(102,02,30000),(103,03,25000),(104,02,36000);
select * from orders;
select c.cstm_name,o.order_id,o.order_amount from customer c inner join orders o on c.cstm_id=o.cstm_id;
select c.cstm_name,o.order_id,o.order_amount from customer c inner join orders o on c.cstm_id=o.cstm_id where o.order_amount>4000;
create table employee(emp_id int primary key auto_increment,emp_name varchar(50),dept_id int, salary int, join_date date);
insert into employee(emp_name,dept_id,salary,join_date)values("keerthi",201,60000,'2026-10-31'),("riya",202,55000,'2026-08-23'),("diya",null,40000,'2026-10-20'),(null,204,46000,'2026-07-01');
select * from employee;
create table dept(dept_id int,dept_name varchar(50));
insert into dept(dept_id,dept_name)values(201,"HR"),(202,"finance"),(203,"sales"),(204,"operations");
select * from dept;
select e.emp_id,e.emp_name,e.dept_id,d.dept_name from employee e left join dept d on e.dept_id=d.dept_id;
select e.emp_id,e.emp_name,e.dept_id,d.dept_name from employee e right join dept d on e.dept_id=d.dept_id;
select e.emp_id,e.emp_name,e.dept_id,d.dept_name from employee e left join dept d on e.dept_id=d.dept_id where d.dept_id= null;
select emp_name from employee where dept_id in(201,202) union select emp_name from employee where dept_id in(202,204);
select emp_name from employee where dept_id in(201,202) union all select emp_name from employee where dept_id in(202,204);
truncate table employee;
alter table employee drop column first_name, drop column last_name;
create table employee_fn(emp_id int primary key auto_increment,first_name varchar(50),last_name varchar(50),salary int, joining_date date);
insert into employee_fn(first_name,last_name,salary, joining_date)values("keerthi","m",50000,'2026-10-31'),("riya","r",45000,'2026-08-23'),("diya","eldho",55000,'2026-10-20'),("akki","p",46000,'2026-07-01');
select * from employee_fn;
select emp_id, concat(first_name, ' ' , last_name) as full_name from employee_fn;
select emp_id, salary, round(salary) as round_salary from employee_fn;
select emp_id, salary, abs(salary) as absolute_salary from employee_fn;
select emp_id, first_name, datediff(curdate(), joining_date) as exp_days from employee_fn;
select emp_id,last_name, left(last_name,3) as new_lstname from employee_fn;
alter table employee drop column join_date;
select avg(salary) from employee;
select emp_id,emp_name,salary from employee where salary>(select avg(salary) from employee);
select emp_id,emp_name,dept_id from employee where dept_id in (select dept_id from dept where dept_name in('sales','HR'));
select max(salary) from employee;
select emp_id,emp_name from employee where salary= (select max(salary) from employee);
create view employee_report as select e.emp_name as Name ,d.dept_name as department, e.salary as Salary from employees e left join dept d on e.dept_id= d.dept_id;
select * from employee_report;
select * from employee_report where salary>50000;